# Deep Learning for Natural Language Processing
## Exercise Sheet 4 - numpy

You should answer each question with a line of code in the cell below.
A correctly completed answer gives 2 points. Partially correct answers give 1 point.

**Submission deadline:** 09/12/2020, 23:59 Central European Time

**Exercise:** 16/12/2020, after the lecture

**Instructions for submission:** 
You should complete the parts of the exercises that are marked as **TODO**. A correctly completed **TODO** gives 2 bonus points. Partially correct answers give 1 bonus point. After completing the exercise, save a copy of the notebook as exercise4_numpy_MATRIKELNUMMER.ipynb, where MATRIKELNUMMER is your matriculation number. Then upload the notebook to moodle (submission exercise sheet 4).

**Note:** In order to understand the code, it can be helpful to experiment a bit during development. You are welcome to print variables, reduce dataset sizes, or experiment with hyperparameters. But please remove these changes before submitting the notebook. If we cannot run your notebook (e.g., because you commented out an important variable, or because a print statement is congesting stdout), then we cannot grade it. 

Total points: 30

* import the numpy package under the name np

In [25]:
import numpy as np

* generate a vector with values ranging from 42 to 80

In [206]:
x = np.arange(42,81)

* revert the previously generated vector

In [207]:
x[::-1]

array([80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64,
       63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47,
       46, 45, 44, 43, 42])

* create a null vector of size 15 but the third, fifth and eight values set to 1

In [138]:
indices = [2, 4, 7]
zero = np.zeros(15)
zero[indices] = 1
zero

array([0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

* create a 4x4 matrix with random values

In [208]:
np.random.rand(4,4)

array([[0.96743173, 0.27150251, 0.86990236, 0.12282471],
       [0.15466663, 0.38269306, 0.51133902, 0.03417213],
       [0.51672075, 0.75759334, 0.30812067, 0.10488937],
       [0.62540184, 0.03889343, 0.82875325, 0.52076687]])

* create a 5x5 2d array with 0 on the borders and 1 inside

In [124]:
random = np.zeros((5,5))
random[1:-1,1:-1] = 1

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

* create a 4x5 2d array with random values and compute the mean values of each row

In [210]:
print(np.random.rand(4,5).mean(1))

[0.29506396 0.61728093 0.44687465 0.54420454]


* create a vector of size 5 with values drawn from an uniform distribution and sort it

In [215]:
np.sort(np.random.uniform(0,1,5))



array([0.06664406, 0.22282543, 0.52082116, 0.79867874, 0.825058  ])

* consider an array of shape (3,4,5), what is the index (x,y,z) of the 30th element? Note that
there is a way to find this index directly within numpy

In [216]:
np.unravel_index(30, (3,4,5))

(1, 2, 0)

* compute the dot product of a 3x4 and a 4x2 matrix, each containing only ones

In [119]:
x = np.ones((3,4))
y = np.ones((4,2))
x.dot(y)

array([[4., 4.],
       [4., 4.],
       [4., 4.]])

* create an array containing all dates of the days you had to work on this sheet including start and
end day in the format YYYY-MM-DD. Hint: there is a special data type for dates in numpy

In [120]:
dates = np.datetime64('2020-12-03')

numpy.datetime64('2020-12-03')

* create a 1d array with 10 random values between 0 and 5 and find the value nearest to 4

In [205]:
rand_arr = 5 * np.random.rand(10)
rand_arr[np.abs(rand_arr-4).argmin()]

3.875881952109921

* considering a four dimensions array, get the sums over the first two axis at once

In [195]:
np.random.rand(2,4,4,2).sum(axis=(0,1))


array([[4.92041144, 3.6313558 ],
       [3.64106795, 4.1595549 ],
       [4.06007213, 4.46767176],
       [4.67542197, 3.82457133]])

* given the array [0,1,2,3,4,5,0,2,3,1,2,3,2,3,2] find the most frequent value and its indexes

In [151]:
x = [0,1,2,3,4,5,0,2,3,1,2,3,2,3,2]
indices = np.where(x == np.bincount(x).argmax()) # np.bincount(x).argmax() for most frequent value
indices


(array([ 2,  7, 10, 12, 14]),)

* given the array [0,0,1,5,0,2,0,0,3,0] find all indexes of non-zero values and all indexes of values
greater than 1

In [158]:
x = [0,0,1,5,0,2,0,0,3,0]
print("non-zero:", np.array(x).nonzero())
print("greater 1:", np.where(np.array(x)>1))

non-zero: (array([2, 3, 5, 8]),)
greater 1: (array([3, 5, 8]),)
